{
  "version": 2,
  "jobs": {
    "build": {
      "docker": [
        {
          "image": "circleci/node:10-browsers"
        }
      ],
      "working_directory": "~/repo",
      "steps": [
        "checkout",
        {
          "restore_cache": {
            "keys": [
              "v1-dependencies-{{ checksum \"package.json\" }}",
              "v1-dependencies-"
            ]
          }
        },
        {
          "run": "stty cols 80"
        },
        {
          "run": "npm run sysinfo"
        },
        {
          "run": "npm run versions"
        },
        {
          "run": "npm config set spin false"
        },
        {
          "run": "npm install"
        },
        {
          "run": "npm run npmls"
        },
        {
          "save_cache": {
            "paths": [
              "node_modules"
            ],
            "key": "v1-dependencies-{{ checksum \"package.json\" }}"
          }
        },
        {
          "run": "npm test"
        }
      ]
    }
  }
}
